In [1]:
import pandas as pd
import re

In [2]:
test = pd.read_csv("data/test.csv",index_col=0)

In [3]:
test

,Unnamed: 0,text_id,full_text
0,0.0,0000C359D63E,when a person has no experience on a job their...
1,1.0,000BAD50D026,Do you think students would benefit from being...
2,2.0,00367BB2546B,"Thomas Jefferson once states that ""it is wonde..."
3,3.0,hp,Dumbledore and Professor McGonagall bent forwa...
4,4.0,tkm,"Being Southerners, it was a source of shame to..."
5,5.0,high school,"With the development of the technology, more a..."
6,6.0,college1,“We need to move to a place with an elevator.”...
7,7.0,college2,In the article “Beyond borders: what it means ...
8,NaN,hp,Dumbledore and Professor McGonagall bent forwa...
9,NaN,tkm,"Being Southerners, it was a source of shame to..."
10,NaN,va,To improve the compositionality of the semanti...
11,NaN,ll,The first Wednesday in every month was a Perfe...
12,NaN,sp,Thou see'st these lovers seek a place to fight...
13,NaN,bp,"Fifteen years later, in 1980, Jintong emerges ..."

In [4]:
test['full_text'] = test["full_text"].replace(re.compile(r'[\n\r\t]'), ' ', regex=True)

In [5]:
length = []
for i in test['full_text']:
    leng = len(i.split())
    length.append(leng)

test['text_length']=length

#30efb9040e0ec8b40219c7025888f89db4a60801

In [6]:
import nltk
from nltk.tokenize import word_tokenize
nltk.download('punkt')

[nltk_data] Downloading package punkt to /Users/yudichen/nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [7]:
text_tag = []
for i in test['full_text']:
    i = word_tokenize(i)
    pos_tagger = nltk.pos_tag(i)
    word_tag = []
    for j in pos_tagger:
        (word,tag) = j
        word_tag.append(tag)
    text_tag.append(word_tag)

In [8]:
import nltk
from nltk.data import load
nltk.download('tagsets')
tagdict = load('help/tagsets/upenn_tagset.pickle')
tagdict.keys()

[nltk_data] Downloading package tagsets to
[nltk_data]     /Users/yudichen/nltk_data...
[nltk_data]   Package tagsets is already up-to-date!

dict_keys(['LS', 'TO', 'VBN', "''", 'WP', 'UH', 'VBG', 'JJ', 'VBZ', '--', 'VBP', 'NN', 'DT', 'PRP', ':', 'WP$', 'NNPS', 'PRP$', 'WDT', '(', ')', '.', ',', '``', '$', 'RB', 'RBR', 'RBS', 'VBD', 'IN', 'FW', 'RP', 'JJR', 'JJS', 'PDT', 'MD', 'VB', 'WRB', 'NNP', 'EX', 'NNS', 'SYM', 'CC', 'CD', 'POS'])

In [9]:
tags = list(tagdict.keys())
tags.append("#")
tags

['LS',
 'TO',
 'VBN',
 "''",
 'WP',
 'UH',
 'VBG',
 'JJ',
 'VBZ',
 '--',
 'VBP',
 'NN',
 'DT',
 'PRP',
 ':',
 'WP$',
 'NNPS',
 'PRP$',
 'WDT',
 '(',
 ')',
 '.',
 ',',
 '``',
 '$',
 'RB',
 'RBR',
 'RBS',
 'VBD',
 'IN',
 'FW',
 'RP',
 'JJR',
 'JJS',
 'PDT',
 'MD',
 'VB',
 'WRB',
 'NNP',
 'EX',
 'NNS',
 'SYM',
 'CC',
 'CD',
 'POS',
 '#']

In [10]:
freq = pd.DataFrame(index=range(0,len(test)),columns=tags)
freq.iloc[:] = 0
freq = freq.astype('int')

In [11]:
from collections import Counter
d = []
for i in text_tag:
    d.append(Counter(i))

In [12]:
for i in range(len(test)):
    for key, value in d[i].items():
        freq[key][i] = value

In [13]:
verb = ["VB","VBG","VBD","VBN","VBP","VBZ"]
wh = ["WDT","WP","WRB","PDT","DT","WP$"] #determiner
connection = ["UH","RP","TO","IN","CC","MD","EX"]
adb = ["RB","RBR","RBS"]
pronoun = ["POS","PRP","PRP$"]
noun = ["NN","NNS","NNP","NNPS","LS"]
adj = ["JJ","JJR","JJS"]
fw = ["FW"] #foreign word
number = ['CD'] #number
punc = ["''","--","(",")",".",",","``","$","#","SYM"]

word_type = [verb,wh,connection,adb,pronoun, noun,adj,fw,number,punc]

In [14]:
test['verb'] = freq[verb].sum(axis=1)
test['wh'] = freq[wh].sum(axis=1)
test['connection'] = freq[connection].sum(axis=1)
test['adb'] = freq[adb].sum(axis=1)
test['pronoun'] = freq[pronoun].sum(axis=1)
test['noun'] = freq[noun].sum(axis=1)
test['adj'] = freq[adj].sum(axis=1)
test['fw'] = freq[fw].sum(axis=1)
test['number'] = freq[number].sum(axis=1)
test['punc'] = freq[punc].sum(axis=1)

In [15]:
test = test[['text_id','full_text','text_length','verb','adj','adb','punc']]

In [16]:
test

,text_id,full_text,text_length,verb,adj,adb,punc
0,0000C359D63E,when a person has no experience on a job their...,835,188,39,45,35
1,000BAD50D026,Do you think students would benefit from being...,386,87,14,16,22
2,00367BB2546B,"Thomas Jefferson once states that ""it is wonde...",442,107,29,26,33
3,hp,Dumbledore and Professor McGonagall bent forwa...,675,126,58,38,96
4,tkm,"Being Southerners, it was a source of shame to...",560,85,36,15,56
5,high school,"With the development of the technology, more a...",287,45,23,13,41
6,college1,“We need to move to a place with an elevator.”...,654,141,59,19,82
7,college2,In the article “Beyond borders: what it means ...,330,72,47,20,30
8,hp,Dumbledore and Professor McGonagall bent forwa...,675,126,58,38,96
9,tkm,"Being Southerners, it was a source of shame to...",560,85,36,15,56
10,va,To improve the compositionality of the semanti...,543,91,52,25,70
11,ll,The first Wednesday in every month was a Perfe...,491,83,41,23,64
12,sp,Thou see'st these lovers seek a place to fight...,549,74,55,31,60
13,bp,"Fifteen years later, in 1980, Jintong emerges ...",647,98,59,30,79